name: Automated test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  automated-test-suite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Get poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Run test scripts
      run: |
        poetry run pytest
